#!/bin/bash
#
# KLP
# 04-29-2015
#_________________________________________________________________________
f=${1:-input.nii.gz}
subj=${2:-subj}
functitle=${3:-functitle}
# mean
cmd="fslmaths $f -Tmean avg"
echo $cmd
$cmd
# std
cmd="fslmaths $f -Tstd std"
echo $cmd
$cmd
# snr
cmd="fslmaths avg -div std snr"
echo $cmd
$cmd
#==========================================================================
# by slice snr report
echo subj,func,slice,min,max,mean,std > by_slice.csv
fslslice snr
for f in snr_slice_*; do
    stats=`fslstats $f -R -m -s`
    echo $subj $functitle ${f:10:4} $stats | awk '{printf("%s,%s,%d,%g,%g,%g,%g\n", $1, $2, $3, $4, $5, $6, $7)}' >> by_slice.csv
    rm -rf $f
done
#==========================================================================
# whole brain snr report
echo subject,func,min,max,nonzeroMean > whole_brain.csv
min_max_nonzeroMean=`fslstats snr -R -M | xargs echo | tr ' ' ','`
echo $subj,$functitle,$min_max_nonzeroMean >> whole_brain.csv
